dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv sync --dev
# command to run tests
script:
  - export PYTHONPATH=.
  - pipenv run mypy
  - pipenv run flake8
  - pipenv run test
